export const ENV = {
  CLERK_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY!,
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL!,
  CLERK_GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_CLERK_GOOGLE_WEB_CLIENT_ID!,
  EXPO_PUBLIC_CLERK_GOOGLE_IOS_CLIENT_ID:process.env.EXPO_PUBLIC_CLERK_GOOGLE_IOS_CLIENT_ID!
};
